// try & catch


try{
    // code test
    alert("hi every one");
    alert(x);
    alert("bye every one");

}catch(err){

    // handle error
    alert("inside catch");
    console.log(err);
    console.log(err.name); 
    console.log(err.message);
}
finally{
    alert("bye every one");
}


// try catch not handel any sintex error
// alert("hi every one");
// alert(x);
// alert("bye every one")